### ISSUE TITLE
Exception thrown when trying out the provided example

### ISSUE THREAD

**Issue by pierce-build-user** [builtamont-oss/play2-scala-pdf#10]
## Context

Running you example, I would expect it to work, instead I experience the following exception:
Could not find a suitable constructor in com.builtamont.play.pdf.PdfGenerator. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.builtamont.play.pdf.PdfGenerator.class(PdfGenerator.scala:53)
  while locating com.builtamont.play.pdf.PdfGenerator

Also, this coed does not compile since your "example" template expect a message, and you call it without.
<hr>

## Definition of Done

Working code, or updated documentation that explain the use of inject into HomeController

**Comment by hhandoko** [comment]
Hi @pierce-build-user , I've just checked by re-running both Play 2.4 and 2.5 examples and they are running fine. Can you please share a snippet of your code?

Regarding passing a message, can you be more specific which part of the code / examples you are referring to?

**Comment by pierce-build-user** [comment]
More or less as the example.
I went for import it.innove.play.pdf.PdfGenerator instead.
But to start with I had 

```
resolvers ++= Seq(
  Resolver.sonatypeRepo("snapshots")
)

libraryDependencies ++= Seq(
 "com.builtamont" %% "play2-scala-pdf" % "1.6.1.P25"
)
```
A view:
```
@(message: String)

@main("Example Page") {
    Image: <img src="/public/images/favicon.png"/><br/>
    Hello world! <br/>
    @message <br/>
}
```

And a home controller:
```
import com.builtamont.play.pdf.PdfGenerator

@Singleton
class HomeController @Inject() (pdfGen: PdfGenerator) extends Controller {    
    def examplePdf = Action { pdfGen.ok(views.html.example(), "http://localhost:9000") }    
}
```
As the example, which don't compile, since the @message is not used in the call. But even with the message, it complains of having no default constructor

**Comment by hhandoko** [comment]
I just realised `ApplicationModule.scala` was not committed as part of the example code, my bad.

The error makes sense now since it's trying to find a resolution for a `PdfGenerator` instance (but it's missing). It should look something like below:

### Play 2.4

``` scala
package com.builtamont.modules

import com.google.inject.{AbstractModule, Provides}
import net.codingwell.scalaguice.ScalaModule

import com.builtamont.play.pdf.PdfGenerator

class ApplicationModule extends AbstractModule with ScalaModule {

  /** Module configuration + binding */
  def configure(): Unit = {}

  /**
   * Provides PDF generator implementation.
   *
   * @return PDF generator implementation.
   */
  @Provides
  def providePdfGenerator(): PdfGenerator = {
    val pdfGen = new PdfGenerator()
    pdfGen.loadLocalFonts(Seq("fonts/opensans-regular.ttf"))
    pdfGen
  }

}
```

### Play 2.5

``` scala
package com.builtamont.modules

import com.google.inject.{AbstractModule, Provides}
import net.codingwell.scalaguice.ScalaModule

import play.api.Environment

import com.builtamont.play.pdf.PdfGenerator

class ApplicationModule extends AbstractModule with ScalaModule {

  /** Module configuration + binding */
  def configure(): Unit = {}

  /**
   * Provides PDF generator implementation.
   *
   * @param env The current Play app Environment context.
   * @return PDF generator implementation.
   */
  @Provides
  def providePdfGenerator(env: Environment): PdfGenerator = {
    val pdfGen = new PdfGenerator(env)
    pdfGen.loadLocalFonts(Seq("fonts/opensans-regular.ttf"))
    pdfGen
  }

}
```

I'll update the repo later today.

**Comment by pierce-build-user** [comment]
Ah. Thanks!

**Comment by hhandoko** [comment]
Hi @pierce-build-user ,

I've pushed the repo update as a PR (refer to the above), please have a look. I have to run now but I'll merge the PR to master sometime tonight. Let me know if the examples works fine for you now.

**Comment by hhandoko** [comment]
Merged in `master`.

**Comment by hhandoko** [comment]
Hi @pierce-build-user , let me know if you still have any problem... Otherwise I'll automatically close this in 48 hours.
