### ISSUE TITLE
Scala 2.12 version?

### ISSUE THREAD

**Issue by denisftw** [builtamont-oss/play2-scala-pdf#12]
Hi!

Do you have any plans for releasing the version for Scala 2.12? It seems that the library already works fine with Play 2.6, but a proper release that supports new Scala would be great.

Thanks!

**Comment by hhandoko** [comment]
Hi @denisftw ,

I hadn't checked for Play 2.6 compatibility, but I'll take your word for it 😀 I'll have a snapshot build by the end of the week.

**Comment by denisftw** [comment]
Thanks @hhandoko ! 

On a closer inspection, they did change a few things, but nothing drastic. 

I built a Scala 2.12/Play 2.6 version from your sources yesterday and apart from updating the versions, I only had to add `guice` as a Play module. Didn't check the tests though, but PDF generation itself worked fine. I'll switch back to your version once it's released, but there is no rush here :)

**Comment by hhandoko** [comment]
Hi @denisftw ,

I've updated `flying-saucer` PDF to latest and added Play 2.6 for Scala 2.11 and 2.12. It's now available as version `2.0.0`. It should be up on Maven Central in 24 - 48 hours.

Let me know how you go.

**Comment by denisftw** [comment]
Hi @hhandoko !

I've just switched back to your release and it (the 2.12 version) seems to be working fine.

Thanks for such a quick update :+1:
